#set up properties
PROJECT_ID: qwiklabs-gcp-00-aebaeca0cadb

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-datastore
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, bigquery
            label: master
        gcp:
            project-id: ${PROJECT_ID:qwiklabs-gcp-00-aebaeca0cadb}
            credentials:
                location: classpath:key.json  
            datastore:
                namespace: ${DATASTORE_NAME:marketplace}  